# Generated by Django 5.0.1 on 2024-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="base_distance_in_km",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="fixed_price",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="km_price",
        ),
        migrations.AddField(
            model_name="pricing",
            name="base_distance",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="per_km_price_non_perishable",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="per_km_price_perishable",
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=6),
            preserve_default=False,
        ),
    ]
