# Generated by Django 5.0.1 on 2024-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_remove_pricing_base_distance_in_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
