# Generated by Django 5.0.1 on 2024-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_alter_item_id_alter_item_type_alter_organization_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="base_distance",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="per_km_price_non_perishable",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="per_km_price_perishable",
        ),
        migrations.AddField(
            model_name="pricing",
            name="total_distance",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
            preserve_default=False,
        ),
    ]
