# Generated by Django 5.0.1 on 2024-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0004_remove_pricing_base_distance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="total_distance",
        ),
        migrations.AddField(
            model_name="pricing",
            name="base_distance",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="per_km_price_non_perishable",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="per_km_price_perishable",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
