# Generated by Django 5.0.1 on 2024-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "delivery",
            "0005_remove_pricing_total_distance_pricing_base_distance_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
