# Generated by Django 5.0.1 on 2024-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0007_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
